### ISSUE TITLE
Roadmap for stable release?

### ISSUE THREAD

**Issue by LeoJHarris** [dansiegel/Prism.Maui#5]
Hi @dansiegel 

Is there any rough ETA when Prism.Maui will be available in stable release? We have a large project that uses prism and are keen to get a bit of idea when we could shift to maui but that would depend on this library obviously.

Thank you in advance!

**Comment by dansiegel** [comment]
Thanks for the interest @LeoJHarris. Right now there is an active PR for support for preview 8. This works for navigating to a single page but is failing when navigating with a FlyoutPage. Since I am having tooling issues and unable to debug at this time I can only say it'll get done as the tooling improves. 

Also keep in mind that due to the current state of the tooling and Maui itself Maui will not go GA with .NET 6 next month, and will instead go GA Q2 2022. You can anticipate that we will have a stable package for it when it goes GA.

**Comment by LeoJHarris** [comment]
@dansiegel perfect 👍 thanks for letting us know. Thanks!
